fail_fast: true
repos:
  - repo: local
    hooks:
      - id: system
        name: mypy
        entry: poetry run tox -e mypy
        pass_filenames: false
        language: system
  - repo: local
    hooks:
      - id: system
        name: isort
        entry: poetry run isort .
        pass_filenames: false
        language: system
